### ISSUE TITLE
cannot import name 'BertForSequenceEncoder' from 'transformers'

### ISSUE THREAD

**Issue by mahbub2251** [thunlp/CorefBERT#1]
In the FEVER folder, the train.py file has this dependency -- "from transformers import BertTokenizer, BertForSequenceEncoder, RobertaTokenizer, RobertaForSequenceEncoder" 

But I get this error message for both **BertForSequenceEncoder** and **RobertaForSequenceEncoder** like following 

ImportError: cannot import name 'BertForSequenceEncoder' from 'transformers' (C:\ProgramData\Anaconda3\lib\site-packages\transformers\__init__.py)

The other 2 are being imported

**Comment by YeDeming** [comment]
I guest the problem is about module path.

In this code, we create softlink from the directory "./transformers" to "fever/transformers".  It may not be available for Windows.

You can create the softlink manually or copy the train.py to the same directory with "./transformers".
