### ISSUE TITLE
max_coref_np

### ISSUE THREAD

**Issue by houliangxue** [thunlp/CorefBERT#10]
你好，我有几个疑问：
1、gen_copy_data_memmap.py第15行
parser.add_argument("--max_coref_np", type=int, default=8, help="the maximum numbers of coreference instance stored in numpy memmap, the others are stored in pickle file")
这里的max_coref_np是什么意思，为什么要用pickle file去存储coreference instance
2、paper里CorefBERT只在sentence-level coreference resolution任务上做了测试，用到其他的coreference model上在Ontonotes数据集上会有效果吗？

**Comment by YeDeming** [comment]
你好,
1.  数据部分存在memmap部分存在pickle，访问读取的时候不用全部载入memmap的部分，节约内存
2. 初步尝试了一下，在Ontonotes上没有效果

**Comment by houliangxue** [comment]
好的，谢谢
