### ISSUE TITLE
Code of coreference resolution task

### ISSUE THREAD

**Issue by Syarotto** [thunlp/CorefBERT#11]
Hi, 

I was wondering if you could release the code as in section 4.5 coreference resolution? 

Thank you!

**Comment by YeDeming** [comment]
We use code of [WikiCREM](https://github.com/vid-koci/bert-commonsense) to train and evaluate the coreference resolution. 

Best,
Deming

**Comment by Syarotto** [comment]
Thank you!

**Comment by Syarotto** [comment]
Hi, 

I wonder if there's a way to run corefBERT on coreference resolution task with my own data. I noticed that the pretrained model is based on huggingface/transformers, while WikiCREM uses torch to load pretrained models. 

Thank you!

**Comment by YeDeming** [comment]
WikiCREM uses a older version of huggface. Hence, there is a a little difference.
