### ISSUE TITLE
Is it possible to release a roberta-base model as well?

### ISSUE THREAD

**Issue by allanj** [thunlp/CorefBERT#2]
Since large models are not really practical for us to deploy, but roberta did have a large jump on the QUOREF dataset. Do you plan to release a CorefRoberta-base model?

**Comment by YeDeming** [comment]
Hi,

I uploaded the CorefRoBERTa-base model just now. Hope that it is helpful for you.

Best,
Deming

**Comment by allanj** [comment]
Great.
