### ISSUE TITLE
Problems about pretraining

### ISSUE THREAD

**Issue by jc-ryan** [thunlp/CorefBERT#4]
Hello, there is an error in the script 'run_pretrain.py'
when excute the import command
` from transformers import BertForCopy, RobertaForCopy
`
error occurs "Cannot find reference 'BertForCopy' in '__init__.py' "
Actually，there is not a model called 'BertForCopy' neither in transformers modules nor in the original transformer package
Did you miss it？

**Comment by YeDeming** [comment]
The code is here:

https://github.com/thunlp/CorefBERT/blob/90c349ca5718118272cf17533fc36c96a5067709/transformers/modeling_bert.py#L1272-L1377

**Comment by jc-ryan** [comment]
ok, thanks.
