### ISSUE TITLE
Test coreference resolution on raw text.

### ISSUE THREAD

**Issue by aakashb95** [thunlp/CorefBERT#6]
I have downloaded the base pretrained model from google drive and want to test it on the following raw text:
"My dad and my mum are working hard. She is always nice but he is sometimes rude."

How should i go about using the model to predict coreferences on above text?

I would then want to resolve the coreferences. I have used [this function](https://github.com/shellshock1911/allennlp/blob/cb006899ddb1b0ced4330a9ec823941a014ba03f/allennlp/predictors/coref.py#L76) from allenai for SpanBERT model.

**Comment by YeDeming** [comment]
Sorry, CorefBERT cannot do end-to-end coreference resolution. It can solve the coreference of GAP format. I recommand you to use this code https://github.com/mandarjoshi90/coref for end-to-end coreference resolution

**Comment by aakashb95** [comment]
Thanks for the prompt response.
