### ISSUE TITLE
预训练文件中BertForCopy的问题

### ISSUE THREAD

**Issue by anshiquanshu66** [thunlp/CorefBERT#8]
您好，我在运行run_pretrain.py文件报如此错误是怎么回事，还请给与解答。谢谢！
还有run_pretrain.py文件中from transformers import (WEIGHTS_NAME, BertConfig, BertForMaskedLM, BertTokenizer,
                                  GPT2Config, GPT2LMHeadModel, GPT2Tokenizer,
                                  OpenAIGPTConfig, OpenAIGPTLMHeadModel, OpenAIGPTTokenizer,
                                  RobertaConfig, RobertaForMaskedLM, RobertaTokenizer,
                                  DistilBertConfig, DistilBertForMaskedLM, DistilBertTokenizer, 
                                  BertForCopy, RobertaForCopy) 这里的import的transformers是项目中那个transformers文件，不是那个安装的那个transformers==2.1.1包，对吧。
Traceback (most recent call last):
  File "run_pretrain.py", line 28, in <module>
    from  transformers import (WEIGHTS_NAME, BertConfig, BertForMaskedLM, BertTokenizer,
ImportError: cannot import name 'BertForCopy' from 'transformers' (/home/xxx/anaconda3/envs/czd/lib/python3.7/site-packages/transformers/__init__.py)
Traceback (most recent call last):
  File "run_pretrain.py", line 28, in <module>
Traceback (most recent call last):
    from  transformers import (WEIGHTS_NAME, BertConfig, BertForMaskedLM, BertTokenizer,  File "run_pretrain.py", line 28, in <module>

ImportError: cannot import name 'BertForCopy' from 'transformers' (/home/xxx/anaconda3/envs/czd/lib/python3.7/site-packages/transformers/__init__.py)
    from  transformers import (WEIGHTS_NAME, BertConfig, BertForMaskedLM, BertTokenizer,
ImportError: cannot import name 'BertForCopy' from 'transformers' (/home/xxx/anaconda3/envs/czd/lib/python3.7/site-packages/transformers/__init__.py)
Traceback (most recent call last):
  File "run_pretrain.py", line 28, in <module>
    from  transformers import (WEIGHTS_NAME, BertConfig, BertForMaskedLM, BertTokenizer,
ImportError: cannot import name 'BertForCopy' from 'transformers' (/home/xxx/anaconda3/envs/czd/lib/python3.7/site-packages/transformers/__init__.py)
Traceback (most recent call last):
  File "run_pretrain.py", line 28, in <module>
    from  transformers import (WEIGHTS_NAME, BertConfig, BertForMaskedLM, BertTokenizer,
ImportError: cannot import name 'BertForCopy' from 'transformers' (/home/xxx/anaconda3/envs/czd/lib/python3.7/site-packages/transformers/__init__.py)
Traceback (most recent call last):
  File "run_pretrain.py", line 28, in <module>
    from  transformers import (WEIGHTS_NAME, BertConfig, BertForMaskedLM, BertTokenizer,
ImportError: cannot import name 'BertForCopy' from 'transformers' (/home/xxx/anaconda3/envs/czd/lib/python3.7/site-packages/transformers/__init__.py)
Traceback (most recent call last):
Traceback (most recent call last):
  File "run_pretrain.py", line 28, in <module>
  File "run_pretrain.py", line 28, in <module>
        from  transformers import (WEIGHTS_NAME, BertConfig, BertForMaskedLM, BertTokenizer,from  transformers import (WEIGHTS_NAME, BertConfig, BertForMaskedLM, BertTokenizer,

ImportErrorImportError: : cannot import name 'BertForCopy' from 'transformers' (/home/xxx/anaconda3/envs/czd/lib/python3.7/site-packages/transformers/__init__.py)cannot import name 'BertForCopy' from 'transformers' (/home/xxx/anaconda3/envs/czd/lib/python3.7/site-packages/transformers/__init__.py)

**Comment by YeDeming** [comment]
你好，尝试一下把transformers文件夹放在run_pretrain.py同一个目录

**Comment by anshiquanshu66** [comment]
还是报错
ImportError: cannot import name 'BertForCopy' from 'transformers' (/home/xxx/CorefBERT/Pretrain/transformers/__init__.py)

**Comment by anshiquanshu66** [comment]
放到同一目录下还是报错
ImportError: cannot import name 'BertForCopy' from 'transformers' (/home/xxx/CorefBERT/Pretrain/transformers/init.py)，你所使用的软连接是不是就是Pretrain下面的那个1kb的transfomers文件，transfomers文件中只有一句“../transformers/”，但是没看到哪里有调用这个文件？

**Comment by YeDeming** [comment]
可以把软链接删掉，把整个transformers文件架复制过去试试

**Comment by anshiquanshu66** [comment]
> 可以把软链接删掉，把整个transformers文件架复制过去试试

> 放到同一目录下还是报错
> ImportError: cannot import name 'BertForCopy' from 'transformers' (/home/xxx/CorefBERT/Pretrain/transformers/init.py)，你所使用的软连接是不是就是Pretrain下面的那个1kb的transfomers文件，transfomers文件中只有一句“../transformers/”，但是没看到哪里有调用这个文件？

 就是这么做的，还是报同样的错。ImportError: cannot import name 'BertForCopy' from 'transformers' (/home/xxx/CorefBERT/Pretrain/transformers/init.py)

**Comment by YeDeming** [comment]
好像是__init__.py里漏写了BertForCopy

**Comment by YeDeming** [comment]
感谢你的反馈，`__init__.py`已更新

**Comment by anshiquanshu66** [comment]
> 好像是__init__.py里漏写了BertForCopy

嗯，应该是这个问题，谢谢。
